version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: run tests
          command: pytest --cov=instachatbot
      - codecov/upload:
          file: .coverage

workflows:
  version: 2
  test:
    jobs:
      - build
